version: "3.8"
services: 
  cmt:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: 
          - "node.role == manager"
      mode: global
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  nodenamer:
    image: programkingabel/nodenamer:1.0.1
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: '0.5'
      placement:
        constraints: 
          - "node.labels.zone != 1"
        preferences:
          - spread: node.labels.zone
    ports:
      - "80:80"